services:
  - type: web
    name: insightai
    env: node
    region: singapore
    plan: free
    buildCommand: cd backend && npm install && cd ../frontend && npm install && npm run build
    startCommand: cd backend && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: GROQ_API_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: REACT_APP_FIREBASE_API_KEY
        value: AIzaSyC6tyG7RSVE-UBBmgQUzfSHBTd4EozWVqM
      - key: REACT_APP_FIREBASE_AUTH_DOMAIN
        value: insightai-app-v2.firebaseapp.com
      - key: REACT_APP_FIREBASE_PROJECT_ID
        value: insightai-app-v2
      - key: REACT_APP_FIREBASE_STORAGE_BUCKET
        value: insightai-app-v2.firebasestorage.app
      - key: REACT_APP_FIREBASE_MESSAGING_SENDER_ID
        value: 265470276222
      - key: REACT_APP_FIREBASE_APP_ID
        value: 1:265470276222:web:bf6d6de264c145eb2b1e2f
      - key: REACT_APP_FIREBASE_MEASUREMENT_ID
        value: G-KG6VZSV4E3
